### ISSUE TITLE
Not available on my device Zuk z1

### ISSUE THREAD

**Issue by anilabhadatta** [accelforce/DevOptsHide#1]
I am not able to install it on my device,
I have the latest Magisk installed and the latest LSposed framework.

**Comment by kyori19** [comment]
Where did you try to install the app?
From Play Store?

**Comment by anilabhadatta** [comment]
> Where did you try to install the app?
> From Play Store?

@kyori19 Play store is showing the app isn't available for device. I think it is something related to my processor as it supports 32bit apps only.
Please check if it is possible to release the app for my device (lenovo zuk z1)

**Comment by kyori19** [comment]
Which Android version running on your device?
This app currently supports Android 10 or later.

**Comment by anilabhadatta** [comment]
@kyori19 
I am running Android 9.
Can you make it compatible with Android 9?

**Comment by kyori19** [comment]
I uploaded new version of the app to the store.
Please wait until it will be published.

**Comment by anilabhadatta** [comment]
@kyori19 Okay thanks a lot

**Comment by anilabhadatta** [comment]
@kyori19 I have just tested your app and found out that my app that was detecting developer tools was actually detected ADB debugging .
I kept my developer tools enabled but disabled the ADB debugging and the module as well and now the app is not detected developer tools .
Is it possible to hide ADB debugging from my app with xposed module?

**Comment by kyori19** [comment]
I tried to hide it in v2.0, but I don't know whether it works or not, because I can't guess which method your app uses to detect ADB debugging. Actually I couldn't hide ADB debugging for a bank app on my device.
Anyway, please try when it is published to the store!

**Comment by anilabhadatta** [comment]
@kyori19 Thanks a lot , your app is working perfectly fine.
It is hiding ADB debugging without any issues.

**Comment by kyori19** [comment]
That's nice!
Then I'll close this issue.
