### ISSUE TITLE
Workaround to hide ADB with latest magisk? 

### ISSUE THREAD

**Issue by Magneticdud** [accelforce/DevOptsHide#12]
I'm running latest magisk, in zygote mode, with shamiko and safetynet patch and lsposed.

When I enable your module looks like I can inject it in any app except the ones in the magisk deny list, which are the ones who require it...

The apps in the deny list are greyed out in lsposed manager and when I tick on them, they still detect ADB. With magisk 23 + your plugin instead everything was fine with the same bank app

What workarounds can be used?

For example the dev of this other xposed module for removing screenshot protection applies it system wide: https://github.com/null-dev/LGTweaks/blob/master/app/src/main/java/ax/nd/lgtweaks/systemui/behavior/DisableFlagSecureHook.kt

Disabling ADB each time I want to login to the bank is annoying...

**Comment by kyori19** [comment]
I will check this later but I think it is impossible to apply module system wide...

**Comment by CaptainXLAB** [comment]
You have to disable "Enforce DenyList" in Magisk settings. Enforcing denylist will revert any changes done by root to the app, as if root never existed. Without enforcing, changes will still take place but root will stay hidden.

After disabling enforce option in magisk manager, root changes I made to apps on denylist (like substratum themes, etc) still take effect and apps cannot detect root (although I haven't tried with that many apps, I barely use picky apps on phone)

I have yet to confirm if this setting change allows devoptshide to actually work and properly take effect on apps and keep things hidden, but your main problem where LSposed says that the app is on DenyList in LSposed settings will be solved if you disable enforce denylist setting.

Hope this works for you :)

**Comment by Magneticdud** [comment]
Latest shamiko 0.50 update reverted the behavior to the original one (disable list to enable), so now this xposed patch could work again (shamiko 0.40 would work only if the list was enabled) 

But meanwhile I closed that bank account because I don't trust my money in the hands of someone who just copied and pasted root detection routines from a 10 years old stackexchange post without understanding the reason 😂
