### ISSUE TITLE
Compatibility with root hiding methods

### ISSUE THREAD

**Issue by Megver83** [accelforce/DevOptsHide#13]
I'm using the denegation list in Magisk to hide root from my banking apps as per [this instructions](https://www.reddit.com/r/androidroot/comments/sgg46g/magisk_24_how_to_hide_root_and_should_i_update_to/). However, I cannot enable the module for apps in such list in LSPosed.

**Comment by kyori19** [comment]
There is no way to use DenyList and this module at the same time. There is no solution for this problem.
