### ISSUE TITLE
Doesnt work with Deliveroo Rider

### ISSUE THREAD

**Issue by xxxsskxxx** [accelforce/DevOptsHide#24]
App com.deliveroo.driverapp crashes when this is enabled:-

https://play.google.com/store/apps/details?id=com.deliveroo.driverapp&hl=en&gl=US

Magisk Delta
Lsposed
Latest APK installed

Checked the application in the settings menu

Launch app, it crashes or opens up a browser window to the Rider Support URL

**Comment by vlakoff** [comment]
If I recall correctly, for me DevOptsHide wasn't improving the situation with the Deliveroo Rider app, despite my efforts with the PRs I had submitted.

However, I had discovered that what the app looks for is not the state of the "developer settings", but of the "USB debugging" (in the developer settings, precisely). Try keeping the developer settings, and only disable USB debugging.

(On a related note, time to look for other activites. Deliveroo fares have fallen way below decency.)

**Comment by vlakoff** [comment]
> However, I had discovered that what the app looks for is not the state of the "developer settings", but of the "USB debugging" (in the developer settings, precisely). Try keeping the developer settings, and only disable USB debugging.

Note that it changed some time later: it became mandatory to fully disable the developer settings to use the Rider app. Notably, I needed the developer settings just to disable all those annoying transition effects in the Android interface. I remember the irritation when I forcibly got all these effects back…

**Comment by vlakoff** [comment]
If for any reason you cannot enable Developer options (banking apps, sleazy pimpy Deliveroo, etc.), there is another way to disable these annoying AF animations:

In "Settings > Accessibility" (then possibly in a "Color and motion" subpage), you should find a "Remove animations" toggle.

Sooooo relieving!
