### ISSUE TITLE
Pubg New State is Detecting Developer Option.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [accelforce/DevOptsHide#3]
Android 11 Custom Rom - Nusantara
Magisk v23
Riru v25.4.4
Edxpoded v0.5.2.2

Also ..it is not hiding the developer option but disabling it permanently... i renabled developer option multiple timer ..like 5 times ..but just after enabling developer it get auto disables and doesn't show up in Sttings>System

A guide on how to use the app would be good.

**Comment by wiipowerpc** [comment]
> Android 11 Custom Rom - Nusantara Magisk v23 Riru v25.4.4 Edxpoded v0.5.2.2
> 
> Also ..it is not hiding the developer option but disabling it permanently... i renabled developer option multiple timer ..like 5 times ..but just after enabling developer it get auto disables and doesn't show up in Sttings>System
> 
> A guide on how to use the app would be good.

I've developed a script to bypass ADB detection on PUBG (and any app that may detect it), all you need to do is turn off USB Debugging and run the script file on any root app that allows running them (such as smartpack kernel manager)

https://drive.google.com/file/d/1Iw6lF5aqiFVEP9IeDinj7egrBFzvyuc_/view?usp=sharing
