### ISSUE TITLE
Cannot hide USB Debugging mode from Momo 4.0.1

### ISSUE THREAD

**Issue by zgfg** [accelforce/DevOptsHide#4]
Sorry, I don't know if I'm missing something or what

Installed your module and enabled Momo app:
![IMG_20211113_084137](https://user-images.githubusercontent.com/51943147/141611057-1f17aed2-a1de-4a26-86a2-08ffbc85ae2c.jpg)

Rebooted, cleared Cache and Data for Momo (to forget previous findings), opened Momo but it still reports that Debugging mode is enabled:
![IMG_20211113_084002](https://user-images.githubusercontent.com/51943147/141611066-be233bf7-4e01-4afa-86ce-cedadbca149d.jpg)

I can only prevent Momo from detecting Debugging mode by going to Developer options and disabling USB Debugging mode there (or by disabling the whole Developer options)

Btw, Momo is enabled for MagiskHide - but it has nothing to do with Developer options/USB Debugging

Momo:
https://t.me/magiskalpha : Files
https://www.coolapk.com/apk/io.github.vvb2060.mahoshojo

**Comment by kyori19** [comment]
Can I peek the source code of Momo? I couldn't assume how Momo detecting USB debugging.

**Comment by zgfg** [comment]
Interesting question. Seems it's not publicly available, but these are developers (maybe you, as developer could ask them):
https://github.com/vvb2060
https://github.com/RikkaApps

**Comment by nift4** [comment]
it checks `init.svc.adbd` prop

**Comment by zgfg** [comment]
> it checks `init.svc.adbd` prop

Ok, so it's stopped or running

**Comment by kyori19** [comment]
I think that these apps have to use native C++ code to read system props.
This app cannot hook C++ methods because this is XPosed module.
So I will mark this as wontfix and close this.

If you think my understand is wrong, please reopen this.

**Comment by zgfg** [comment]
> I think that these apps have to use native C++ code to read system props. This app cannot hook C++ methods because this is XPosed module. So I will mark this as wontfix and close this.
> 
> If you think my understand is wrong, please reopen this.

In terminal, with su, you can read without a problem:
getprop init.svc.adbd

and even write:
setprop init.svc.adbd stopped

Hence script can do it

Yand

**Comment by kyori19** [comment]
I could, but that is global change and it might cause side effects.
Moreover, that should be done with Magisk module, not the XPosed module.

**Comment by zgfg** [comment]
> I could, but that is global change and it might cause side effects. Moreover, that should be done with Magisk module, not the XPosed module.

Temporary solution by editing service.d script from USNF module:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-86757541

**Comment by bengalih** [comment]
FYI for anyone who might be finding this, it appears that the later version of Momo (at least starting with 4.4.1) will detect this still even with setting the prop appropriately.  It must be checking a different location to determine debugging status.

**Comment by pmsobrado** [comment]
That's the challenge I guess, to prevent Momo to detect it... although, if this module is enabled for Momo, then Momo will detect LSPosed :(

**Comment by Adil9647** [comment]
Can you tell me how to solve that non SDK interface one

> That's the challenge I guess, to prevent Momo to detect it... although, if this module is enabled for Momo, then Momo will detect LSPosed :(



> Sorry, I don't know if I'm missing something or what
> 
> Installed your module and enabled Momo app: ![IMG_20211113_084137](https://user-images.githubusercontent.com/51943147/141611057-1f17aed2-a1de-4a26-86a2-08ffbc85ae2c.jpg)
> 
> Rebooted, cleared Cache and Data for Momo (to forget previous findings), opened Momo but it still reports that Debugging mode is enabled: ![IMG_20211113_084002](https://user-images.githubusercontent.com/51943147/141611066-be233bf7-4e01-4afa-86ce-cedadbca149d.jpg)
> 
> I can only prevent Momo from detecting Debugging mode by going to Developer options and disabling USB Debugging mode there (or by disabling the whole Developer options)
> 
> Btw, Momo is enabled for MagiskHide - but it has nothing to do with Developer options/USB Debugging
> 
> Momo: https://t.me/magiskalpha : Files https://www.coolapk.com/apk/io.github.vvb2060.mahoshojo

Can you tell me how fix that "restrictions on non SDK interface aren't working" problem?

**Comment by boudywho** [comment]
@Adil9647 suddenly, I started getting the same thing 'Restrictions on non-SDK interfaces is not working' did you figure out how to fix it?

**Comment by boudywho** [comment]
@Adil9647 try this command. 
- ```settings delete global hidden_api_policy```

It worked for me.
