### ISSUE TITLE
Version for Android 8?

### ISSUE THREAD

**Issue by Darkmaster006** [accelforce/DevOptsHide#8]
I have an old phone that can only go as far as Android 8, but I need to hide developer options from an app, is it possible to have a version for Android 8? Sorry for the trouble, and thank you very much.

**Comment by kyori19** [comment]
Ofcource I can but I'm not sure it works or not.
I released new version v2.1 which supports Android 8.0 and later so please try it out.
I will close this issue for now, but if you find any problems feel free to reopen it.

**Comment by Darkmaster006** [comment]
Thank you very much.
